# Generated by Django 5.2 on 2025-04-19 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_alter_products_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ('id',), 'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
    ]
